Fix file watcher bug looking at built-in modules.
fixes #752

The bug shows:
```
2019-05-29T23:34:39Z.128 DEBUG   streamlit.ScriptRunner: ScriptRunner state: RUNNING -> STOPPED
Exception in thread Streamlit script runner thread:
Traceback (most recent call last):
  File "/Users/armando/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/armando/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/armando/st/aaj-st/lib/streamlit/ScriptRunner.py", line 234, in _run
    self._local_sources_watcher.update_watched_modules()
  File "/Users/armando/st/aaj-st/lib/streamlit/watcher/LocalSourcesWatcher.py", line 116, in update_watched_modules
    self._register_watcher(filepath, name)
  File "/Users/armando/st/aaj-st/lib/streamlit/watcher/LocalSourcesWatcher.py", line 64, in _register_watcher
    watcher=FileWatcher(filepath, self.on_file_changed),
  File "/Users/armando/st/aaj-st/lib/streamlit/watcher/EventBasedFileWatcher.py", line 67, in __init__
    file_watcher.watch_file(file_path, on_file_changed)
  File "/Users/armando/st/aaj-st/lib/streamlit/watcher/EventBasedFileWatcher.py", line 145, in watch_file
    folder_handler.add_file_change_listener(file_path, callback)
  File "/Users/armando/st/aaj-st/lib/streamlit/watcher/EventBasedFileWatcher.py", line 225, in add_file_change_listener
    md5 = util.calc_md5_with_blocking_retries(file_path)
  File "/Users/armando/st/aaj-st/lib/streamlit/watcher/util.py", line 54, in calc_md5_with_blocking_retries
    raise e
  File "/Users/armando/st/aaj-st/lib/streamlit/watcher/util.py", line 49, in calc_md5_with_blocking_retries
    with open(file_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/armando/st/aaj-st/examples/built-in'
```

This code snippet shows the problem and is whats implemented.
```
import sys

modules = dict(sys.modules)

for name, module in modules.items():
    spec = getattr(module, '__spec__', None)
    if spec is None:
        filepath = getattr(module, '__file__', None)
        if filepath is None:
            continue
    else:
        filepath = spec.origin
    if filepath is None or filepath in ['built-in', 'frozen']:
        continue
    print(name, filepath)
```

Output before the fix would be
```
_thread built-in
_warnings built-in
_weakref built-in
zipimport built-in
_frozen_importlib_external frozen
_io built-in
marshal built-in
posix built-in
encodings /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/encodings/__init__.py
codecs /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/codecs.py
_codecs built-in
encodings.aliases /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/encodings/aliases.py
encodings.utf_8 /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/encodings/utf_8.py
_signal built-in
__main__ /tmp/foo.py
encodings.latin_1 /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/encodings/latin_1.py
io /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/io.py
abc /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/abc.py
_abc built-in
_bootlocale /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/_bootlocale.py
_locale built-in
site /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/site.py
os /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/os.py
stat /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/stat.py
_stat built-in
posixpath /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/posixpath.py
genericpath /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/genericpath.py
os.path /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/posixpath.py
_collections_abc /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/_collections_abc.py
_sitebuiltins /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/_sitebuiltins.py
types /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/types.py
importlib /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/importlib/__init__.py
importlib._bootstrap_external frozen
warnings /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/warnings.py
importlib.util /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/importlib/util.py
importlib.abc /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/importlib/abc.py
importlib.machinery /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/importlib/machinery.py
contextlib /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py
collections /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/collections/__init__.py
operator /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/operator.py
_operator built-in
keyword /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/keyword.py
heapq /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/heapq.py
_heapq /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/lib-dynload/_heapq.cpython-37m-darwin.so
itertools built-in
reprlib /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/reprlib.py
_collections built-in
functools /Users/armando/.pyenv/versions/3.7.3/lib/python3.7/functools.py
_functools built-in
```

which is why i ignore built-in and frozen